
```{r}
library(ggplot2)
library(plotly)
library(plyr)
library(glue)
```


```{r}
df <- wine <- read.csv(file = "../data/processed/wine_quality.csv")

# need an extra ID column for linking plots ~ Rain
wine$id <- as.character(1:nrow(wine))

# Units in order of variables
units <- c('(g/dm^3)', '(g/dm^3)', '(g/dm^3)', '(g/dm^3)', '(g/dm^3)', '(mg/dm^3)', '(g/cm^3)', '(g/dm^3)', '(%)')

# df <- wine_quality <- read.csv("data/processed/wine_quality.csv")
# gsub("(mg/dm^3)","",colnames(df),fixed = TRUE)->cn
# gsub("(g/dm^3)","",cn,fixed = TRUE)->cn
# gsub("(g/cm^3)","",cn,fixed = TRUE)->cn
# gsub("(%)","",cn,fixed = TRUE)->cn
# str_trim(cn, side = c("right"))->cn
# colnames(df)<-cn


# Eric's code - I like it and would like to use it on my page so it's here now ~ Luka :)
variables <- colnames(wine) # Just rename all vars instead of some <--> subset(df, select = -c(Wine, Quality.Factor, Quality.Factor.Numeric)))

variablesNoUnits <- gsub("\\.\\..*$","", variables) # Remove units
variablesNoUnits <- gsub("\\."," ", variablesNoUnits) # Replace dots with spaces
# IF THIS GENERATES A PARSE ERROR ANYWHERE, simply replace "varibale name with space" --> "`varibale name with space`"

colnames(wine) <- variablesNoUnits

## Luka
# I could probably put this in the wrangling file
factors <- c(1, 13, 14, 15)
wine[, -factors] <- as.numeric(unlist(wine[, -factors]))
white <- wine[wine[,'Wine']=='white', ]
red <- wine[wine[,'Wine']=='red', ]
wine_type <- list('White' = white, 'Red' = red)


mu_white <- ddply(white, "`Quality Factor`", numcolwise(mean))
mu_red <- ddply(red, "`Quality Factor`",  numcolwise(mean))
mu_type <- list(mu_white, mu_red)

vars <- variable.names(wine)[-15] %>% as.vector()
```

```{r}
### ORIGINAL OPERATION ###

density_plot <- function(winetype = 2, variable = 12) {
  
  coln <- sym(colnames(wine)[variable])

  ggplot(wine_type[[winetype]], aes(x = !!coln, fill = Quality.Factor)) +
    
    geom_density(alpha = 0.4) +
    geom_vline(data=mu_type[[winetype]], aes(xintercept=!!coln, color=Quality.Factor), linetype="dashed", size=0.9) +
    ggtitle(glue('{coln} Quality Factor Distribution'), subtitle = glue('For {names(wine_type[winetype])} Wine')) +
    theme_classic() +
    theme(legend.title = element_text('Quality Levels'),
          legend.position = c(0.94,0.88),
          text = element_text(size = 12),
          element_line(size = 0.3),
          panel.grid.major = element_line(color = '#ededed')) +
    ylab('Density') + xlab(coln)
}

```

```{r}
test <- function(variable, winetype) {
    coln <- sym(colnames(wine)[variable])

    plot <- ggplot(wine_type[[winetype]], aes(x = !!coln, fill = `Quality Factor`)) + 
            geom_density(alpha = 0.4) + ylab('Density') +
            geom_vline(data=mu_type[[winetype]], aes(xintercept=!!coln, color=`Quality Factor`), linetype="dashed", size=0.5) +
            ggtitle(glue('{coln} Distribution at Varying Quality Levels'), subtitle = glue('For {names(wine_type[winetype])} Wine')) +
            theme_classic() +
            theme(legend.title = element_text('Quality Levels'),
                  legend.position = c(0.85,0.85),
                  text = element_text(size = 12),
                  element_line(size = 0.3),
                  axis.text.y = element_blank(), axis.ticks.y = element_blank())
    
  return(plot) #ggplotly(plot))
}

test(3, 2)
```


```{r}
par(mfrow = c(2,2))

density_plot(1, 2)
density_plot(1, 4)
density_plot(1, 8)
density_plot(1, 10)

density_plot(2, 3)
density_plot(2, 5)
density_plot(2, 7)
density_plot(2, 9)


```



```{r}
df <- wine <- read.csv("../data/processed/wine_quality.csv")

colnames(wine)
variables <- colnames(wine) # Just rename all vars instead of some <--> subset(df, select = -c(Wine, Quality.Factor, Quality.Factor.Numeric)))
variablesNoUnits <- gsub("\\.\\..*$","", variables) 
variablesNoUnits <- gsub("\\."," ", variablesNoUnits) 

colnames(wine) <- variablesNoUnits

## Luka
# I could probably put this in the wrangling file
factors <- c(1, 13, 14, 15)
wine[, -factors] <- as.numeric(unlist(wine[, -factors]))
white <- wine[wine[,'Wine']=='white', ]
red <- wine[wine[,'Wine']=='red', ]
wine_type <- list('White' = white, 'Red' = red)


mu_white <- ddply(white, "`Quality Factor`", numcolwise(mean))
mu_red <- ddply(red, "`Quality Factor`",  numcolwise(mean))
mu_type <- list(mu_white, mu_red)

med_white <- ddply(white, "`Quality Factor`", numcolwise(median))
med_red <- ddply(red, "`Quality Factor`",  numcolwise(median))
med_type <- list(med_white, med_red)

mode_white <- ddply(white, "`Quality Factor`", numcolwise(contmode))
mode_red <- ddply(red, "`Quality Factor`",  numcolwise(mode))
mode_type <- list(mode_white, mode_red)

stats <- list(mu_type, med_type, mode_type)

vars <- variable.names(wine)[-15] %>% as.vector()

stats
white[, 3]

contmode <- function(vector) {
  dens <- density(vector)
  maxx = dens$x[which.max(dens$y)]
  return(maxx)
}

contmode(white[,3])

dens$x
```


```{r}
library(corrplot)

eric <- function(x, y, winetype, quality) {
  
    winex <- subset(wine, Wine %in% winetype)
    winex <- subset(winex, `Quality Factor Numeric` %in% quality)

    colx <- sym(colnames(winex)[x])
    coly <- sym(colnames(winex)[y])

    p <- ggplot(winex, aes(x = !!colx, y = !!coly)) + geom_bin2d() +
      scale_fill_gradient(low="lightgray", high = "darkred") +
      theme_minimal() +
      geom_smooth(method = lm)
    
    return(p)
}
eric(2, 2, list('white', 'red'), list(0,1,2))
```

```{r}

colnames(wine)[2:12] %>% purrr::map(function(col) list(label = col, value = which(colnames(wine)[2:12]==col)))

```


























